name: Build and publish Docker image to GHCR

on:
  push:
    branches: [ feature/provma-preview, main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ___PROVMAR_01_
          file: ___PROVMAR_01_/Dockerfile.preview
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/provma-preview:latest
            ghcr.io/${{ github.repository_owner }}/provma-preview:${{ github.sha }}
